# original source: errr-maxx-builds/android-setup-build-env
name: Setup gradle environment for building APKs

inputs:
  usePatchedSDK:
    required: false
    type: boolean
    default: false

runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: gradle

    - uses: android-actions/setup-android@v3
      with:
        log-accepted-android-sdk-licenses: false

    - name: Download modified 33-34 SDK android.jar files
      if: ${{ inputs.usePatchedSDK }}
      run: |
        TARGET='/usr/local/lib/android/sdk/platforms'
        SOURCE='https://github.com/Reginer/aosp-android-jar/raw/main'
        curl -Lo "$TARGET/android-33/android.jar" "$SOURCE/android-33/android.jar"
        curl -Lo "$TARGET/android-34/android.jar" "$SOURCE/android-34/android.jar"
      shell: bash

    - run: |
        sed -i 's/\r$//' gradlew
        chmod +x gradlew
      shell: bash

    - run: |
        {
          echo
          echo 'org.gradle.caching=true'
          echo 'org.gradle.parallel=true'
          echo 'org.gradle.vfs.watch=true'
          echo 'org.gradle.jvmargs=-Xmx2048m' # Increase heap size
        } >> gradle.properties
      shell: bash

    - uses: actions/cache@v4 # wrapper
      with:
        path: ~/.gradle/wrapper
        key:          ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle-wrapper.properties') }}
        restore-keys: ${{ runner.os }}-gradle-wrapper-

    - uses:  actions/cache@v4 # dependencies
      with:
        path: ~/.gradle/caches !~/.gradle/caches/build-cache-*
        key:          ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle*', 'gradle.properties') }}
        restore-keys: ${{ runner.os }}-gradle-caches-

    - uses:  actions/cache@v4 # build
      with:
        path: ~/.gradle/caches/build-cache-*
        key:          ${{ runner.os }}-gradle-builds-${{ github.sha }}
        restore-keys: ${{ runner.os }}-gradle-builds-