name: Build (debug)
description: Builds debugging android apk
inputs:
  KEYSTORE_BASE_64:
    description: 'secrets.KEYSTORE_BASE_64'
    required: false
  RELEASE_KEYSTORE_ALIAS:
    description: 'secrets.RELEASE_KEYSTORE_ALIAS'
    required: false
  RELEASE_KEYSTORE_PASSWORD:
    description: 'secrets.RELEASE_KEYSTORE_PASSWORD'
    required: false
  RELEASE_KEY_PASSWORD:
    description: 'secrets.RELEASE_KEY_PASSWORD'
    required: false
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        cache: 'gradle'
        java-version: 17
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Download modified 33-34 SDK android.jar files
      run: |
        TARGET="$ANDROID_SDK_ROOT/platforms"
        SOURCE='https://github.com/Reginer/aosp-android-jar/raw/main'
        curl -Lo "$TARGET/android-33/android.jar" "$SOURCE/android-33/android.jar"
        curl -Lo "$TARGET/android-34/android.jar" "$SOURCE/android-34/android.jar"
      shell: bash

    - name: Set APP_NAME
      shell: bash
      run: |

        # Setup GITHUB_SHA
        if [[ "$GITHUB_EVENT_NAME" = 'pull_request' ]]; then
          GITHUB_SHA="${{ github.event.pull_request.head.sha }}" # Do not use last merge commit set in GITHUB_SHA
        fi
        GITHUB_SHA="${GITHUB_SHA:0:7}"

        # App/apk name
        APP_NAME="${{ github.event.repository.name }}-${GITHUB_SHA}"
        echo APP_NAME="$APP_NAME" >> "$GITHUB_ENV"

    - name: Build Debug
      if: ${{ github.event_name != 'release'  }}
      uses: ./.github/actions/build-debug

    - name: Build Release
      if: ${{ github.event_name == 'release'  }}
      uses: ./.github/actions/build-release
      with:
        KEYSTORE_BASE_64: ${{ inputs.KEYSTORE_BASE_64 }}
        RELEASE_KEYSTORE_ALIAS: ${{ inputs.RELEASE_KEYSTORE_ALIAS }}
        RELEASE_KEYSTORE_PASSWORD: ${{ inputs.RELEASE_KEYSTORE_PASSWORD }}
        RELEASE_KEY_PASSWORD: ${{ inputs.RELEASE_KEY_PASSWORD }}


    - name: Upload Release Build to Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.APP_NAME }}
        path: ${{ env.APK_FILE }}